setup.py
Addressing the comment mentioned [here](https://github.com/getsentry/pypi/pull/968#issuecomment-2341865629) on minimum python version being 3.10
=> fix(python): Reduce minimum python version required to 3.10

requirements.in, requirements.txt
In order for sentry-infra-tools to be published in sentry's pypi, lets use the typing versions already available there.
Deliberately not using the newer versions of other packages in order to inadvertently breaking existing tooling.
=> chore(requirements): Fix dependencies based on sentry pypi

config_builder/generate_topic_data.py, setup.py
The generate_raw_topic_data has implicit knowledge of the hierarchy of the directories it works with. This breaks when using sentry infra tools since the tools are installed in different directories. Allow it to take a root directory argument and pass it in the make materialize command of ops repo for integration to work.
```bash
~/w/ops  nikhars/fix/..-infra-tools !1 ?1  make materialize
ok | direnv  .venv-sentry-kube py | 3.11.7  py  14:15:50
generate-raw-topic-data --root-dir ./shared_config
Generating raw topic data
shared_config/shared_config/kafka/topics/generated/_generated_raw_topic_data.json
materialize-config -c -o _materialized_configs --root-dir ./shared_config/
Validating yaml file schemas
Combining individual source files
Materializing jsonnet files
[GENERATED] …
```
=> fix(materialize): Take root directory as argument

sentry_kube/cli/kafkactl.py, sentry_kube/validate_services.py
Sync between SHAs b65df3da50166daec95facef9ca44d8ebfed525b to a864cafd6a4771434bab51c79b7773877c8342d7
Diff
```bash
diff --git a/k8s/cli/sentry_kube/cli/kafkactl.py b/k8s/cli/sentry_kube/cli/kafkactl.py
index abd0d12e6..98baef2f1 100644
--- a/k8s/cli/sentry_kube/cli/kafkactl.py
+++ b/k8s/cli/sentry_kube/cli/kafkactl.py
@@ -47,7 +47,7 @@ def kafkactl(ctx):
delete=False,
only_delete=False,
selective_delete=None,
-        root=True,
+        root=False,
safe_to_evict=False,
memory=None,
)
@@ -68,7 +68,7 @@ def kafkactl(ctx):
delete=False,
only_delete=True,
selective_delete=None,
-        root=True,
+        root=False,
safe_to_evict=False,
memory=None,
)
diff --git a/k8s/cli/sentry_kube/validate_services.py b/k8s/cli/sentry_kube/validate_services.py
index b37f42afa..88431b028 100644
--- …
```
=> chore(sync): Sync changes till a864cafd6a4771434bab51c79b7773877c8342d7

requirements.txt, sentry_kube/cli/pg/__init__.py, sentry_kube/cli/pg/create_user.py, sentry_kube/ext.py
Sync from ops repo between SHA a864cafd6a4771434bab51c79b7773877c8342d7 and 134da6c507d2ee342575762cb3e47cc25b898767
Diff is as shown below
```shell
diff --git a/k8s/cli/requirements.in b/k8s/cli/requirements.in
index a191efc06..5e2d52e49 100644
--- a/k8s/cli/requirements.in
+++ b/k8s/cli/requirements.in
@@ -39,6 +39,8 @@ google-crc32c>=1.5.0
google-cloud-compute>=1.18.0
google-cloud-os-login>=2.14.3
+# pg/create_user.py
+google-cloud-secret-manager>=2.20.2
rich
diff --git a/k8s/cli/requirements.txt b/k8s/cli/requirements.txt
index 7f674b769..03c89a642 100644
--- a/k8s/cli/requirements.txt
+++ b/k8s/cli/requirements.txt
@@ -44,6 +44,7 @@ google-api-core==2.20.0
+    #   google-cloud-secret-manager
google-api-python-client==2.147.0
google-auth==2.35.0
@@ -54,6 +55,7 @@ google-auth==2.35.0 …
```
=> Sync till 134da6c507d2ee342575762cb3e47cc25b898767

README.md, requirements.txt
This PR adds contents to the README file with regards to how to install sentry-infra-tools in editable mode. Editable mode may be desired when developing software on sentry-kube but wanting to test in some other virtual environment.
Created a new virtual environment. Installed the regular sentry-infra-tools package from pypi. Then removed the package from virtual environment and installed the local residing sentry-infra-tools package. Removed the `kube` output to see that `sentry-kube --help` indeed took the change into effect. The diff used for testing was
```shell
diff --git a/sentry_kube/cli/__init__.py b/sentry_kube/cli/__init__.py
index 531f7a3..34f154a 100644
--- a/sentry_kube/cli/__init__.py
+++ b/sentry_kube/cli/__init__.py
@@ -85,19 +85,6 @@ def _configure_colors(ctx):
) …
```
=> chore(readme): sentry-infra-tools in editable mode

.envrc, devenv/config.ini, devenv/sync.py
Lets move towards using devenv for setting up the development environment since too many ways of setting dev environment was cited as one of the concerns when working with too many repos.
```shell
~/w/sentry-infra-tools  nikhars/feat/devenv ?2  rm -rf .venv/
~/w/sentry-infra-tools  nikhars/feat/devenv ?2  devenv sync
ensuring sentry-infra-tools venv at .venv...
virtualenv doesn't exist or is using an outdated python, recreating at .venv...
syncing sentry-infra-tools with /Users/nikharsaxena/workspace/sentry-infra-tools/requirements-dev.txt...
~/w/sentry-infra-tools  nikhars/feat/devenv ?2  make tools-test
pytest -vv .
============================================= test session starts =============================================
platform darwin -- Python 3.11.6, pytest-8.3.3, pluggy-1.5.0 …
```
=> feat(devenv): Use devenv for setup

libsentrykube/tests/test_utils.py, libsentrykube/utils.py, sentry_kube/validate_services.py
Since the service registry is moving to its own repository, we need a mechanism to get the relevant data from there. This PR introduces a mechanism which first checks whether the service registry package is installed or not. If yes, uses the file from the package. If not, falls back to hardcoded path from before.
Added this test code to see the path being resolved
```shell
def test_get_service_registry_package_installed():
path = get_service_registry_filepath()
print(path)
```
Output
Without the sentry-service-registry, notice the path
```shell
~/w/sentry-infra-tools/l/tests  nikhars/fix/service-registry +2 !2 ?2  pytest -vv test_utils.py::test_get_service_registry_package_installed -s
============================================== test session starts …
```
=> fix(service_registry): Dynamic detection of path

libsentrykube/tests/test_utils.py, libsentrykube/utils.py
We were looking at the wrong path when looking for the JSON file
=> fix(service-registry): Use the correct path to find JSON file

libsentrykube/kube.py, libsentrykube/service.py, libsentrykube/tests/conftest.py, libsentrykube/tests/k8s_root/clusters/saas/customer.yaml, libsentrykube/tests/k8s_root/services/service1/region_overrides/us/customer.managed.yaml, libsentrykube/tests/k8s_root/services/service1/region_overrides/us/customer.yaml, libsentrykube/tests/k8s_root/services/service4/_values.yaml, libsentrykube/tests/k8s_root/services/service4/region_overrides/us/customer.managed.yaml, libsentrykube/tests/k8s_root/services/service4/region_overrides/us/customer.yaml, libsentrykube/tests/test_kube.py, libsentrykube/tests/test_service.py
The quickpatch tool was supposed to patch directly the region override files
for each service.
Sadly w ecould not find a viable yaml parser that would preserve comments.
We are likely going to build one eventually. Till then, though, this seems
the only option to allow any tool make changes to our value files.
We add a second override file: `cluster.managed.yaml`. This file can be
rewritten by tools, so you should not add comments. It can be updated by hand,
(though why?) as tools are patching the file rather than regenerating it.
The override happens right after the region override.
=> Introduce an added override file to be managed by tools

libsentrykube/quickpatch.py, libsentrykube/tests/test_data/quickpatches/test-patch-no-file.yaml, libsentrykube/tests/test_quickpatch.py, sentry_kube/cli/__init__.py, sentry_kube/cli/quickpatch.py
Wire up what we built.
Specifically:
1. create three subcommands (they are arguments, not subcommands). One for render, diff and apply 
2. Implement diff and render. Tested against s4s and it works 
3. Added a rudimentary parsing of arguments from the command line
3. Fixed the quickpatch module in case the managed file is not there. Now it gets created 
4. Tested against a test patch in snuba s4s.
What is missing (separate PRs)
- validation of the arguments according to the types defined in the jsonschema in the patch
- figure out how to express a patch that is able to either update fields or create paths 
- implement apply 
- add the git part
=> Wire up patches into sentry-kube quickpatch

devenv/config.ini, devenv/sync.py
Some of the sentry-kube functionality need `gcloud` to be installed.
The devenv for sentry-infra-tools did not install it.
=> Add the gcloud CLI to the devenev setup

libsentrykube/quickpatch.py, libsentrykube/tests/test_data/quickpatches/invalid-schema1.yaml, libsentrykube/tests/test_data/quickpatches/invalid-schema2.yaml, libsentrykube/tests/test_data/quickpatches/invalid-schema3.yaml, libsentrykube/tests/test_data/quickpatches/test-patch-missing-mappings.yaml, libsentrykube/tests/test_data/quickpatches/test-patch-missing-schema.yaml, libsentrykube/tests/test_data/quickpatches/test-patch-override.yaml, libsentrykube/tests/test_data/quickpatches/test-patch.yaml, libsentrykube/tests/test_data/quickpatches/test-patch2.yaml, libsentrykube/tests/test_data/values/default2.managed.yaml, libsentrykube/tests/test_data/values/empty.managed.yaml, libsentrykube/tests/test_quickpatch.py
This PR deprecates the use of jsonpatch in quickpatch and instead uses our own patcher:
The patcher interprets the paths defined in the .managed.yaml file according to a few rules:
1. Paths must be separated by `/`
2. Paths must refer to nested json objs in the corresponding values file that is being patched
3. If the json obj in the `.managed.yaml` file does not exist, the patcher will auto-generate all of the relevant objs as needed & defined by the patch
4. If the values file does not exist, the patcher will also auto-generate the `.managed.yaml` file
5. Any values that are defined in the patch will be set at the path location. Aka, the patcher may override existing objs at the defined path. To avoid this issue, specify the full length of the path down to the lowest-nested level, with …
=> Use own jsonpatch implementation

config_builder/materialize_all.py, config_builder/materializer.py, config_builder/test_materializer.py
This PR adds support for additional import paths (specifically, python packages) during jsonnet materialization. 
This can be used via the `--ext-package=python_package_name` cli argument
=> chore(service-registry): Add python package import solution

libsentrykube/events.py, sentry_kube/cli/apply.py, sentry_kube/cli/edit_secret.py, sentry_kube/cli/kubectl.py, sentry_kube/cli/run_job.py, sentry_kube/cli/run_pod.py
`--quiet` currently doesn't apply to DD reporting, it should so that we can pipe output from `sentry-kube` (mainly `kubectl`) into other things.
=> fix: --quiet should mute DD echos

libsentrykube/kube.py, libsentrykube/service.py, libsentrykube/tests/conftest.py, libsentrykube/tests/test_kube.py, libsentrykube/tests/test_service.py, libsentrykube/utils.py
This PR adds two possibilities to share common config between cluster configs.
* Hierarchical Sharing: it is possible to introduce an additional directory between `region_overrides` and `region_name` with arbitrary names. This directory can contain a `_values.yaml` file with config values where all values from `region_name/cluster.yaml` are merged into.
* Cluster Sharing: it is possible to add a `_values.yaml` file into `region_overrides/region_name` which works conceptually the same as the hierarchical sharing but it makes more sense if many cluster files exist in a region
=> feat(sentrykube): introduce additional possibilities to override config

libsentrykube/service.py
The new hierarchy structure did not convert "saas" into "us", breaking the config generation by simply moving a "us" named folder in a hierarchy folder.
This PR also applies the conversion in the hierarchy
=> fix(libsentrykube): apply name conversion in the entire config tree

libsentrykube/ext.py
This way, some templates can be run with additional context, and made
reusable, see https://github.com/getsentry/ops/pull/13275
=> feat: Allow additional locals to md5template

libsentrykube/service.py
This PR fixes accidental group name mapping which can occur by calling `get_service_value_override_path`.
There is not much benefit in using the function and instead we can just build the desired path inline.
=> fix(libsentrykube): prevent accidental mapping of group dir name

libsentrykube/service.py
When a region override exists, but it is empty, parsing fails. Instead the empty file should just be treated as empty.
`safe_load` returns `None` if the file contains no YAML documents (aka when it is empty).
Came up in: https://github.com/getsentry/ops/pull/13594
```
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/home/runner/work/ops/ops/.venv/lib/python3.11/site-packages/sentry_kube/validate_services.py", line 89, in <module>
test_services()
File "/home/runner/work/ops/ops/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/runner/work/ops/ops/.venv/lib/python3.11/site-packages/click/core.py", line …
```
=> fix(kube): Ignore empty override files

libsentrykube/ext.py
1. deployment and statefulset had different hardcodes.
2. eu calls sometimes were failing with 1s timeout for me.
=> change: allow kube api calls timeout overrides in ext.py

libsentrykube/ext.py
Some of our SREs were experiencing regular timeouts when communicating with clusters in `jp`.
Increase default timeout from 1s -> 3s to provide a bit of wiggle room for global communication.
=> Increase default kube api timeout

libsentrykube/ext.py, libsentrykube/setup.py, setup.py
There is common pattern of having a default variable value for service, redefinition for environment, redefinition for component + some hardcoded default in yaml itself.
This macro allows to convert chains like this
```
{% set sdk_environment = params.sdk_environment|default(values.sdk_environment)|default(customer.sentry_region) %}
```
into this
```
{% set sdk_environment = get_var('sdk_environment', params, values, customer)
```
=> change: Add get-var macro

libsentrykube/service.py, libsentrykube/tests/test_service.py
We should support .j2 extensions since these are Jinja2 files.
=> fix: Support .yaml.j2 extensions for templates

README.md, libsentrykube/iap.py, libsentrykube/tests/test_iap.py, sentry_kube/cli/__init__.py
Originally, we had to connect to GKE clusters via some DNS hacking & port forwarding.
GCP now officially supports connecting to clusters via an external DNS endpoint (which we added in #72), this removes the old way of connecting (and doesn't require people to update their `/etc/hosts` anymore)
=> feat(kubectl): remove old private DNS connection to clusters

cli_config/configuration.yaml, libsentrykube/config.py, libsentrykube/tests/config.yaml, libsentrykube/tests/test_config.py
Reverts getsentry/sentry-infra-tools#65 the default assumptions break our event reporting so this needs to be reworked.
=> Revert "chore: Add config defaults"

sentry_kube/cli/pg/create_user.py, sentry_kube/tests/cli/test_pg.py
It will be possible to create plaintext secrets in namespaces other than `default`, for example:
```
sentry-kube -C s4s pg create-user --generate-plaintext --plaintext-k8s-secret sentry-system/datadog --username kafka-password
```
P.S. At this point, `pg` subcommand could also be used for creating secrets for systems other than Postgres, so we may consider renaming it.
=> sentry-kube pg: support optional namespace via /

libsentrykube/helm.py, libsentrykube/kube.py, libsentrykube/service.py, libsentrykube/tests/k8s_root/services/service1/_values_consumers.yaml, libsentrykube/tests/k8s_root/services/service1/region_overrides/us/customer.managed.yaml, libsentrykube/tests/k8s_root/services/service1/region_overrides/us/customer_consumers.yaml, libsentrykube/tests/test_kube.py, libsentrykube/tests/test_service.py
**Context:**
streaming team needs github CODEOWNERS to consumer values so they can merge changes without depending on SRE aproval
**PR explained:**
for every level of overriding logic, find all files that start with the keyword (usually it will be the default value of `_values`) and combine them together, before proceeding with the original overriding logic
**Impacts:**
for services that only has one `_values.yaml` file, this changes nothing
**Rollout plan:**
after this PR is merged, cut a new release, update sentrykubelib version in ops, then make a new `_consumer_values.yaml` file in `getsentry` service, in all overriding levels
=> feat(sentry-kube): support combining files with keyword

cli_config/configuration.yaml, libsentrykube/config.py, libsentrykube/tests/config.yaml, libsentrykube/tests/test_config.py, sentry_kube/cli/__init__.py
We want to fix some bad region naming, this allows regions to be referenced by an alias so we don't have to have duplicate regions in our config leading to other messes.
=> feat: support region aliases

sentry_kube/ext.py
We already have `use_auth=True` in all invocations of `pgbouncer_sidecar()` so it should be fine to remove unused code.
Tested with:
```
pip install -e ~/code/sentry-infra-tools
make materialize-k8s-service service=getsentry
make materialize-k8s-service-st service=getsentry
```
=> chore(pgbouncer): use auth unconditionally

libsentrykube/ext.py, sentry_kube/cli/apply.py
When deploying new things we don't want to query Prod for the image as we don't have anything to query so support passing in an image.
=> feat: Allow setting an override image SHA from the CLI for applies

libsentrykube/utils.py, sentry_kube/cli/debug.py, sentry_kube/cli/kubectl.py
Use [kubectl debug](https://kubernetes.io/docs/reference/kubectl/generated/kubectl_debug/) subcommand but with some additions:
* use the same image for debug as the original container being debugged;
* remove security features for debug purposes (read-only file system, low-privileged user).
Thanks to [custom profiling in kubectl debug](https://kubernetes.io/blog/2024/08/22/kubernetes-1-31-custom-profiling-kubectl-debug/) (since 1.31 hence the version bump):
* pass the same env variables as the original container;
* attach the same volumes as the original container;
* however, some volumes (with `subPath`) are disallowed for ephemeral containers, hence we do the symlink workaround.
Try it out locally:
```
pip install -e /Users/oioki/code/sentry-infra-tools
```
Example of usage:
```
$ …
```
=> feat(sentry-kube): add `debug` subcommand

libsentrykube/customer.py, libsentrykube/events.py, sentry_kube/cli/__init__.py
When using aliases, we should pass back the proper region name so things like reporting send the actual region and not the alias.
=> fix: Pass back region_name when using alias so lookups always work

sentry_kube/cli/debug.py
Fixes this issue:
```
The Pod "relay-6b7b775cfb-wsh9v" is invalid: spec.ephemeralContainers[4].volumeMounts[2].mountPath:
Invalid value: "/subPathMounts/etc/relay": must be unique
```
=> fix(debug): Filter duplicated mount paths

sentry_kube/cli/run_pod.py
We don't run celery works anymore, update the default deployment to use the `web` deployment
=> chore: Update default ST deployment
