getsentry/sentry-infra-tools

- .github/workflows/sentry-kube-ci.yml
- .github/workflows/type-checking.yml
- Makefile
- mypy.ini
- requirements-dev.txt
This has been inspired from https://github.com/getsentry/ops/blob/master/.github/workflows/type-checking.yaml
> feat(mypy): Add mypy github actions

- setup.py
Adds typing to the packages so that the mypy run in packages which use sentry infra tools can succeed
```bash
~/w/ops  nikhars/fix/..-infra-tools !3  pip install sentry-infra-tools --no-cache-dir
ok  3s  direnv  .venv-sentry-kube py | 3.11.7  py  12:27:51
Requirement already satisfied: sentry-infra-tools in ./.venv-sentry-kube/lib/python3.11/site-packages (0.0.7)
Requirement already satisfied: anyio==4.4.0 in ./.venv-sentry-kube/lib/python3.11/site-packages (from sentry-infra-tools) (4.4.0)
Requirement already satisfied: attrs==24.2.0 in ./.venv-sentry-kube/lib/python3.11/site-packages (from sentry-infra-tools) (24.2.0)
Requirement already satisfied: bcrypt==4.1.3 in ./.venv-sentry-kube/lib/python3.11/site-packages (from sentry-infra-tools) (4.1.3)
Requirement already satisfied: …
```
> chore(typing): Add typing to package

- libsentrykube/git.py
- libsentrykube/quickpatch.py
- sentry_kube/cli/quickpatch.py
Add the basic structure of the quickpatch tool
> Add quickpatch tool scaffolding

- config_builder/materializer.py
This PR just moves out the import_callback into its own function (so that it can be imported & called elsewhere)
> Move out the callback

- sentry_kube/cli/apply.py
This adds a `--allow-jobs` flag to `sentry-kube diff/apply` which when set will allow diff/apply to spawn jobs.
This is needed for INC-984 as we need to spawn a large number of pods each with unique CLI args, so jobs are the best way to do this (and `run_job` only allows creating a single job and is less supported than `diff/apply`).
> INC-984: allow diff/apply to spawn jobs

- libsentrykube/iap.py
- libsentrykube/ssh.py
- sentry_kube/cli/ssh.py
Gcloud no longer seems to need them to figure out where to go.
> Removes the region and zone parameters from the ssh command.

- libsentrykube/tests/conftest.py
https://github.com/getsentry/sentry-infra-tools/pull/67 missed removing this test code.
> chore: Remove unused EB test code

- assistant/prdocs.py
- assistant/test_prdocs.py
- simplify intro
- move changed files into details block
> clean up ops assistant message

- libsentrykube/reversemap.py
- sentry_kube/render_helm_services.py
> feat(helm): add reversemap support

- libsentrykube/helm.py
- sentry_kube/cli/helm.py
> Minor helm enhancements

- README.md
Install instructions were still from when this was in the ops repo
I think you just have to run this script, if I'm missing anything please lmk
> fix(readme): update install info

- libsentrykube/helm.py
- libsentrykube/service.py
SSIA
This also fix a breaking change on the helm commands introduced by 01d644f.
> fix: helm with OCI repos

- libsentrykube/linear.py
- sentry_kube/cli/detect_drift.py
tested locally via command line
> added Linear integraiton for Drift tickets and swapped it in 

- .github/workflows/sentry-kube-ci.yml
- libsentrykube/tests/test_lint.py
at least locally, the length assertion and list of lint issues wasnt right..
> (test): fix test_lint failures

- libsentrykube/customer.py
- sentry_kube/cli/__init__.py
https://github.com/getsentry/sentry-infra-tools/pull/124 didn't cover all scenarios, this fixes our alias look ups from all references.
> fix(config): Aliases aren't used every where

- libsentrykube/ext.py
- sentry_kube/ext.py
Adding optional `security_hardened` parameter to `geoip_initcontainer()` and `pgbouncer_sidecar()`. This will allow to cleanup a few security concerns.
> feat(k8s): security hardening of geoip and pgbouncer sidecar

- libsentrykube/kube.py
- libsentrykube/service.py
- libsentrykube/tests/test_service.py
https://ttl255.com/jinja2-tutorial-part-3-whitespace-control/
> PRODENG-159: add service-level feature flag for simplified jinja whitespace handling

- libsentrykube/helm.py
Ticket: PRODENG-140
Specifically: support blue-green deployment strategy
> feat: add helm release strategies

- sentry_kube/cli/get_image.py
when an undefined service is passed, the cmd will return "unknown" instead of an error
> PRODENG-227: handle unknown services

- libsentrykube/helm.py
> fix: helm `get_remote_app_version`

- libsentrykube/helm.py
- sentry_kube/cli/helm.py
> feat: add helm namespace filter

- libsentrykube/helm.py
Fix the fact that helm re-uses more of the k8s service logic than I initially thought, meaning it also needs to use the merge config.
Test Plan:
Works against https://github.com/getsentry/ops/pull/16885
> fix: merge config for helm contexts

- libsentrykube/helm.py
> fix: merge arguments passed in Helm functions
